// Code generated by "stringer -type MoveType -linecomment"; DO NOT EDIT.

package aptos

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MoveType_Bool-0]
	_ = x[MoveType_Uint8-1]
	_ = x[MoveType_Uint64-2]
	_ = x[MoveType_Uint128-3]
	_ = x[MoveType_Address-4]
	_ = x[MoveType_Signer-5]
	_ = x[MoveType_Vector-6]
	_ = x[MoveType_Struct-7]
}

const _MoveType_name = "move_type_boolmvoe_type_u8move_type_u64move_type_u128move_type_addressmove_type_signermove_type_vectormove_type_struct"

var _MoveType_index = [...]uint8{0, 14, 26, 39, 53, 70, 86, 102, 118}

func (i MoveType) String() string {
	if i >= MoveType(len(_MoveType_index)-1) {
		return "MoveType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MoveType_name[_MoveType_index[i]:_MoveType_index[i+1]]
}
